name: Android APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # KORREKTUR: Wir wechseln zu einer anderen, stabileren Buildozer Action
      - name: Build with Buildozer
        uses: aacebo/buildozer-action@v1.4.1
        id: buildozer

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          # Der Pfad zum Artefakt ist bei dieser Action leicht anders.
          path: ${{ steps.buildozer.outputs.apk_file_path }}
