name: Android APK Build (Manually)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libffi-dev \
              libssl-dev \
              build-essential \
              python3-dev \
              libgirepository1.0-dev \
              libcairo2-dev \
              cython3

      - name: Install Buildozer
        run: pip install --upgrade buildozer

      - name: Install python-for-android dependencies
        run: pip install --upgrade cython virtualenv

      - name: Run Buildozer
        run: buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk # Findet die APK im Standard-Ausgabeordner
