name: Android APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: acebo/buildozer-action@v1  # KORREKTUR: Wir verwenden die stabile Hauptversion v1
        id: buildozer

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.apk_file_path }}
